apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pdyh2evf4-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/pdyh2evf4-java-quarkus-gitops